Override deploy:shared task to handle pimcore php config files
w-vision/pimcore-deployer pull request #2
Opened 2018-03-28 13:45 UTC by davidhoeck

2018-03-28 13:50 UTC, dpfaffenbauer requested changes

2018-03-28 13:50 UTC, dpfaffenbauer commented on recipes/pimcore.php
> +task('deploy:shared', function () {
can we rename that to ```deploy:pimcore:shared:config``` and introduce another configuration ```pimcore:shared_configurations``` to configure them? I don't think it as a good idea to have them static and overwrite a default function of deployer.

2018-03-28 13:50 UTC, dpfaffenbauer commented on recipes/pimcore.php
> +    foreach (get('shared_dirs') as $dir) {
remove this completely as we introduce a new task

2018-03-28 13:50 UTC, dpfaffenbauer commented on recipes/pimcore.php
> +    foreach (get('shared_files') as $file) {
use ```pimcore:shared_configurations```

2018-04-03 12:51 UTC, dpfaffenbauer requested changes

2018-04-03 12:51 UTC, dpfaffenbauer commented on deploy.sample.php
> +    'var/config/extensions.php',
can you please remove the extensions.php? this one should come from the repository.

2018-04-03 12:51 UTC, dpfaffenbauer commented on recipes/pimcore.php
> +        run("if [ grep -q '[^[:space:]]' < '$sharedPath/$configFile' ]; then echo '$emptyContent' >> '$sharedPath/$configFile'; fi");
this doesn't seem to work for me, but this did:

```php
run("[ -s '$sharedPath/$configFile' ] || echo '$emptyContent' >> '$sharedPath/$configFile'");
```

2018-04-03 13:18 UTC, dpfaffenbauer requested changes

2018-04-03 13:18 UTC, dpfaffenbauer commented on deploy.sample.php
> +    'var/config/customviews.php'
this shouldn't be there as well, causes an pimcore failure when it returns empty array

2018-04-03 13:19 UTC, dpfaffenbauer commented on deploy.sample.php
> +    'var/config/customviews.php'
same for perspectives.... doesn't show any tree views (documents, assets, objects) when empty

2018-04-03 18:40 UTC, dpfaffenbauer approved these changes

2018-04-03 18:40 UTC, merged

2018-04-04 06:55 UTC, aarongerig commented
@davidhoeck Thanks for the effort and @dpfaffenbauer thanks for reviewing! ;)